### PR TITLE
conflict fix with random module

### PR DESCRIPTION
**Pull request by talhasch**
Raises "AttributeError: 'module' object has no attribute 'choice'" on python2 (2.7.10) because module name (of random plugin) conflicts with python's random module.

### CODE REVIEW

**Comment by hanks** [comment]
I also hit this, need to rename `random.py` to other name

**Comment by zeroSteiner** [comment]
Thanks for reminding me about this, I'll take a look soon.

**Comment by zeroSteiner** [comment]
Yup, I can reproduce this.

```
python example/example.py 
Formatters for app1:
       input: This is a cool demo text to show this functionality.
   lowercase: this is a cool demo text to show this functionality.
      secret: xxxx xx x xxxx xxxx xxxx xx xxxx xxxx xxxxxxxxxxxxx.
   uppercase: THIS IS A COOL DEMO TEXT TO SHOW THIS FUNCTIONALITY.

Formatters for app2:
       input: This is a cool demo text to show this functionality.
   lowercase: this is a cool demo text to show this functionality.
Traceback (most recent call last):
  File "example/example.py", line 79, in <module>
    main()
  File "example/example.py", line 69, in main
    run_demo(app2, source)
  File "example/example.py", line 53, in run_demo
    print('  %10s: %s' % (name, fmt(source)))
  File "example/./app2/plugins/random.py", line 9, in make_random
    chars[idx] = random.choice(string.ascii_letters)
AttributeError: 'module' object has no attribute 'choice'
```

**Comment by zeroSteiner** [comment]
Landed, thanks alot for this submission!

**Pull request merged**
