### PR TITLE
Add python >3.7 support and remove deprecated yield_fixture

### LINKED ISSUE #21: please add python >3.7 support
it would be good to have an official release

### PR DESCRIPTION
**Pull request by AltF02**
Hello @mitsuhiko,

This pr closes #21, the library itself looks like it already fully works with python 3.8+. I've ran all the tests

### CODE REVIEW

**Comment by blshkv** [comment]
There are 2 failed checks, both using deprecated python versions (2.7 and 3.3). You might want just to remove both.

**Comment by DankDumpster** [comment]
Yeah, looks like it just failed on retrieving the python binary.

**Comment by blshkv** [comment]
can you try to adjust .travis.yml as well? still fails ;-) Also, remove it from setup.py to be inline.

**Comment by DankDumpster** [comment]
Sorry my bad, I need my coffee

**Comment by zeroSteiner** [comment]
Changes look good to me. Thanks for updating this. They'll be incorporated into the upcoming v1.0.1 release which I'll publish shortly.

I considered bumping the major version for this but since 2.x compatibility is retained through 2.7, I opted to just bump the patch number.

**Pull request merged**
